### ISSUE TITLE
Error getnum

### ISSUE THREAD

**Issue by JuanIgnacioBridoux** [PI-ITBA/2023_02#1]
Hola buenas tardes. Quería consultar cuál es la causa del siguiente error. Muchas gracias!

<img width="766" alt="Sin título" src="https://github.com/PI-ITBA/2023_02/assets/142061801/36f4278b-b40d-4664-a906-c56c8b2a5178">

**Comment by ImNotGone** [comment]
Fijate que pusiste el genum.h en vez del getnum.c cuando estabas compilando

**Comment by JuanIgnacioBridoux** [comment]
Ahí va, muchas gracias!

**Comment by ImNotGone** [comment]
:D
