### ISSUE TITLE
TP6_ej4: Complejidad del algoritmo

### ISSUE THREAD

**Issue by tomaspietravallo** [PI-ITBA/2023_02#10]
Buenos dias!

Me disculpo por abrir un nuevo issue para el mismo ejercicio ( Issue #9 ), no me queda claro si debería abrir otro o utilizar el existente, para evitar confusiones abrí uno nuevo por si acaso.

Mis preguntas son en cuanto a la complejidad tiempo/memoria del ejercicio. Luego de pensar bastante y explorar diferentes alternativas, logre llegar a un algoritmo que a mi entender es de complejidad lineal para tiempo y memoria.

El código en cuestión es el siguiente, y verifica todos los asserts del [test dado por la cátedra](https://drive.google.com/file/d/1tDtzhUSqgHCUJWd9G9OGnqKfgzYfoNs1/view?usp=sharing)

<details>

<summary>Consigna</summary>

```c
// Consigna:
// Ejercicio 4 ** (resuelto en video)
// Escribir una función que reciba un vector desordenado de números enteros y su dimensión,
// y construya otro vector eliminando los valores repetidos.
// La función deberá retornar en su nombre la dimensión del nuevo vector
// (La función solicitada  no debe superar las 10 líneas).
```

</details>

<details>

<summary>Click para expandir y mostrar el codigo</summary>

```c
//
// Created by Tomas Pietravallo - ITBA on 30/08/2023.
//

#include <stdio.h>
#include <assert.h>

// Headers
unsigned int hashmapKey(int id, unsigned int mod);
int eliminaRepetidos( const int original[], int dimOrig, int resultado[]);

unsigned int hashmapKey(int id, unsigned int mod){
    // Utilizo una diofantica en el rango [0-mod*5]
    // Esto permite garantizar una correspondencia unica entera para cada numero [0-mod]
    // Utilizado para chequear de manera eficiente las repeticiones
    // 2 & 3 son los primos mas pequeños que se pueden utilizar, y resultan en el limite superior 5*mod
    // Los modulos utilizan dos numeros consecutivos de modo que sean coprimos entre si, garantizando la unicidad
    // El modulo en si esta para evitar números mayores a la dimension del arreglo original cayendo fuera de rango
    // Esta efectivamente también funciona para números negativos. Se asume mod != 0
    return 2 * ( id % mod ) + 3 * ( id % (mod <= 2 ? mod + 1 : mod - 1) );
}

int eliminaRepetidos( const int original[], int dimOrig, int resultado[] ){
    // Used together with hashmapKey function
    int hashmap[dimOrig * 5];
    // Init as zeros
    for (int i = 0; i < dimOrig * 5; ++i) {
        hashmap[i] = 0;
    }

    int r = 0; // Index for "resultado", will become the new array's dim
    for (int i = 0; i < dimOrig; ++i) {
        unsigned int key = hashmapKey(original[i], dimOrig);
        if (!hashmap[key]) {
            resultado[r] = original[i];
            r++;
        }
        hashmap[key]++;
    }

    return r;
}
```

> Perdon por el uso mixto de ingles y español

</details>

Si no estoy olvidándome de nada, el algoritmo tomaría una cantidad lineal de tiempo respecto del tamaño del arreglo, y se utilizarían `5n` espacios de memoria sin contar los arreglos que se utilizan como parámetros de entrada/retorno

1. Mi duda [1] es si un algoritmo de este estilo (con el uso de Hashmaps/tables) es esperado de nosotros, o si habria alguna otra solucion a explorar para lograr complejidad lineal sin recurrir a estos. La funcion que utilice para el hash fue una diofantica con modulos para limitar la complejidad de memoria utilizando algo de los conocimientos de Algebra del cuatrimestre pasado

2. Una de las ideas era sacrificar memoria y simplemente usar los mismos `int`s como indices pero dado que el arreglo puede contener cualquier entero, la tabla para verificar si un valor ya fue incluido debería contener `UINT_MAX` valores de memoria, lo cual sonaba bastante malo. Efectivamente es una pésima idea, verdad?

3. (En un examen) Si uno optara escribir un código de este estilo (asumamos que efectivamente tiene complejidad lineal) y comete pequeños errores (entiéndase para este issue: el acceso de un array es arr[i] cuando debería ser arr[i+1], o si uno utiliza números negativos la función de hashing falla y repite valores, no se considero el caso de un arreglo de longitud cero, etc), este aun se consideraría mejor que un intento perfecto con complejidad cuadrática respecto del tamaño del arreglo? 

4. Si uno siguiera las normas de Indian Hill, el código al que llegue superaría las 10 lineas? (Aun me cuesta un poco evaluar definitivamente si supere el limite o no en estos casos mas jugados con la cantidad)

Entiendo que estas preguntas son un poco generales y quizás sea difícil responder sin casos concretos, pero me gustaría saber en lineas generales que es lo que se espera/busca para las correcciones de exámenes parciales y guías de ejercicios

Saludos y muchas gracias! - Tomas

**Comment by ImNotGone** [comment]
Buenos dias!? jasdjasdj
No se esperaba que utilicen hashMaps ahora, de todas formas el que tiene la ultima palabra es Marcelo. No lo mire tanto, pero al usar hashTables hay q tener cuidado con las colisiones y bueno obviamente la busqueda es O(1) pero en consecuencia la complejidad espacial incrementa. Igual comentaste que no tendria colisiones. Y respecto a lo que mencionaste de UINT_MAX, fijate que tu tabla si dimOrig excediera 1/5 de UINT_MAX tendria espacios inutiles (?
Dsp quizas lo reviso mejor pero para q tengas una minima respuesta

**Comment by ImNotGone** [comment]
Respecto al 3. no corrijo yo, pero este creo que era esperado que lo resuelvan en O(n^2). Revisando hasta la dim del vec de respuesta para no recorrer de mas. Si lo no lo vi, lo agrego, si lo vi ya lo habia cargado antes asi q sigo con el proximo numero.

4. Lo de las lineas tengo entendido que es mas para que se limiten un poco ustedes. Tambien esperaria quizas que te responda @marcelogarberoglio

**Comment by tomaspietravallo** [comment]
Jajajaj muchas gracias @ImNotGone por la respuesta rápida y disculpa la hora, creí que recién iban a mirarlo mañana jaja

> Y respecto a lo que mencionaste de UINT_MAX, fijate que tu tabla si dimOrig excediera 1/5 de UINT_MAX tendria espacios inutiles

Buena observación, otra cosa que no considere es el caso donde el ID se vaya de rango y de overflow.. aunque me gustaria saber si estos casos hay que considerarlos también, o si _"""siempre se pueden asumir números razonables y no `MAX_INT-1` como parte del arreglo"""_? (estaría mal utilizar `long` como parte del calculo del indice para evitar esto, aunque en la mayoria de casos un simple `int` sea suficiente?)

La tabla siempre tiene espacios vacíos esparcidos entre cada entrada, pero seria interesante ver como faltaría el código con arreglos >1/5 UINT_MAX ya que el indice se iría del rango permitido por un arreglo en C ([creo que el standard solo establece un minimo de 65535](https://stackoverflow.com/a/31864574)), lo cual es otro caso en el que me gustaria saber si habria que contemplar (en general, no solo para este ejercicio/solucion) o si se pueden esperar arreglos/enteros _""razonables""_

> Lo de las lineas tengo entendido que es mas para que se limiten un poco ustedes. Tambien esperaria quizas que te responda \marcelogarberoglio

Dale no hay problema ni apuro, mil gracias y buenas noches

**Comment by martinAleB** [comment]
Buenas noches! @tomaspietravallo 
Esta bueno que pienses en este tipo de soluciones. De todas maneras no es lo que se espera en la materia.
Igualmente estuve analizando la función hashmapKey y no garantiza la unicidad. Por ejemplo:

hashmapKey(0, 5): 2*(0%5) + 3*(0%4) = 0
hashmapKey(20, 5): 2*(20%5) + 3*(20%4) = 0

Con lo cual, si se ejecuta a eliminaRepetidos con el siguiente vector:

int original[] = {0, 20, 1, 1, 1};

La función guardaría en el vector resultado {0, 1}, salteándose la aparición del 20.

De todas formas, sugiero esperar una respuesta de Marcelo.

**Comment by tomaspietravallo** [comment]
> Esta bueno que pienses en este
> Igualmente estuve analizando la función hashmapKey y no garantiza la unicidad. Por ejemplo:
> 
> hashmapKey(0, 5): 2*(0%5) + 3*(0%4) = 0
> hashmapKey(20, 5): 2*(20%5) + 3*(20%4) = 0

Muchas gracias por tomarte el trabajo @martinAleB , anoche me quedé pensando un rato y también encontré un par de colisiones (en retrospectiva intentar asignarle un valor único a cada uno de los posibles infinitos enteros en un rango acotado era ambicioso) 😅

El error es bastante grave, y lo correcto probablemente sería hacer algún tipo de chequeo secundario si el key ya está en uso, aunque se volvía bastante más complicado. Lección aprendida: _no usar hashmaps por ahora_ jaja, pero me gustaría saber cómo habría afectado este error por ejemplo en una corrección  

> De todas formas, sugiero esperar una respuesta de Marcelo.

No hay problema, mil gracias y saludos! ❤️

**Comment by marcelogarberoglio** [comment]
Hola, hago honor a lo que Gonzalo dijo sobre que tengo la última palabra y hago mi aporte: 
1) Si bien es encomiable que investiguen o busquen alternativas, todos los ejercicios se pueden resolver con los temas vistos en clase, por lo que no es necesario que usen en las guías y parciales estructuras de datos o algoritmos como el planteado en tu solución
2) En esta materia además se busca que implementen algoritmos lo más genéricos posibles, si bien el ejercicio pide vector de enteros, podríamos pedirles hacer lo mismo para vector de doubles, o de strings, y no tendrían que pensar algo distinto para cada caso
3) Si bien la solución es más eficiente en cantidad de recorridos, necesita un vector auxiliar 5 veces más grande que el original, lo cual podría limitar su uso si el vector original es muy grande
4) En cuanto a la cantidad de líneas, la función tiene 11. El objetivo detrás de limitar la cantidad de líneas es que no repitan código o -en casos como este- que utilicen funciones auxiliares

Con respecto a tu pregunta 3) como ya te dijo Gonzalo se esperaba que lo resuelvan en O(n^2), que es como está resuelto en la guía; y los ejercicios del parcial serán similares a los de la guía o clases de taller, no vamos a corregir diciendo por ejemplo "este ejercicio nosotros lo resolvimos en O(n^2) y sin usar vector auxiliar, pero uds tendrían que haber pensado una solución O(n) original". Obviamente si aplican alguna solución innovadora y funciona bien y no es muy ineficiente no le vamos a decir "tendrían que haber usado nuestra solución", pero si no sirve para resolver el problema o es más ineficiente que la vista en la cursada, entonces está mal.

**Comment by tomaspietravallo** [comment]
Muchas gracias @marcelogarberoglio y a todos los profes/ayudantes ! Quedo todo claro, cierro el issue (si algún compañero quiere comentar siéntase libre de reabrirlo)
