### ISSUE TITLE
TP6_ej13: Uso de punteros

### ISSUE THREAD

**Issue by tomaspietravallo** [PI-ITBA/2023_02#11]
Buenas! Estaba realizando el ej 13 de la guía 6 y encontré esta forma de realizar el ejercicio (pasa todos los asserts):

<details>

<summary>Codigo (click para expandir)</summary>

```c
#define DIMMAX 4

int productoVectorial(const int * filI, const int * colJ, unsigned int dim){
    int suma = 0;
    for (int i = 0; i < dim; ++i) {
        suma += filI[i] * colJ[dim * i];
    }
    return suma;
}

void productoMat(int matrizA[][DIMMAX], int matrizB[][DIMMAX], int out[][DIMMAX], unsigned int dim){
    for (int i = 0; i < dim; ++i) {
        for (int j = 0; j < dim; ++j) {
            out[i][j] = productoVectorial(matrizA[i], &matrizB[0][j], dim);
        }
    }
}
```

</details>

Mi duda es si realizar algo de este estilo seria correcto. Básicamente use la sintaxis de punteros junto con la dimensión (que es dato) para poder recorrer la columna y hacer el producto matricial. Me choca un poco estéticamente usar `[0]` en `&matrizB[0][j]` y por eso decidí consultarlo

```c
int productoVectorial(const int * filI, const int * colJ, unsigned int dim){
    // ...
    suma += filI[i] * colJ[dim * i];
```

```c
void productoMat() {
    // ...
    out[i][j] = productoVectorial(matrizA[i], &matrizB[0][j], dim);
```

---

También quería aprovechar y consultar como deberíamos darnos cuenta que deberíamos utilizar constantes como `DIMMAX`, la regla que sigo actualmente para armar los prototipos es que los argumentos del prototipo van en el mismo orden que la consigna los menciona, y como por lo general la dimensión/columnas son el ultimo dato mencionado, no lo puedo usar en la declaración de los parámetros con forma de matriz, por lo que necesito un `#define`... seria correcto seguir este razonamiento en el parcial? (el nombre de la constante en un parcial, la elijo yo, o nos van a dar un nombre de ser necesario?)

Muchas gracias, saludos!

**Comment by ImNotGone** [comment]
El codigo parece estar bien. De todas formas podrias hacerlo de la siguiente forma tambien, en lo personal siento que este codigo es mas facil de leer.
```c
int filasXColumnas(const int fila[], const int m2[][DIMMAX], int col, int dim) {
  int total = 0;
  for(int i = 0 ; i < dim ; i++) {
    total += fila[i]*m2[i][col];
  }
  return total;
}

void productoMat( const int m1[][DIMMAX], const int m2[][DIMMAX], int m3[][DIMMAX], int dim) {
  for(int i = 0 ; i < dim ; i++)
    for(int j = 0 ; j < dim ; j++) {
      m3[i][j] = filasXColumnas(m1[i], m2, j, dim);
    }
}```
Despues lo de las macros es para que no queden numeros sueltos dando vueltas, al definir una macro solo lo tenes que cambiar en 1 lugar.

**Comment by ImNotGone** [comment]
La idea de las macros tambien es que no queden "Magic numbers" dando vueltas. En mi examen por ejemplo teniamos que pasar una imagen, representada como una matriz de rgb, a escala de grises. Cuando habia que definir las proporciones de rojo, verde y azul que eran un par de numeros, yo directamente puse algo asi:
```c
grey_px = red * 0.28 + green * 0.35 + blue * 0.37;
```
me restaron puntos por tener magic numbers y deberia haber tenido algo asi
```c
#define RED_WEIGHT 0.28
#define GREEN_WEIGHT 0.35
#define BLUE_WEIGHT 0.37
...
grey_px = red * 0.28 + green * 0.35 + blue * 0.37;
```

**Comment by marcelogarberoglio** [comment]
En realidad el código no está bien, no podés pasar una "columna"  de una matriz a una función. En tu caso funciona únicamente porque la matriz es cuadrada y se usa completa (ergo, el test no estaba del todo completo). Actualizamos el programa de test con el siguiente caso, probalo y vas a ver que no funciona


  int res3[][3] = {
    {14,24,43},
    {84,124,223},
    {154,224,403}
  };
  
  // No usamos la matriz completa
  productoMat(m1, m2, m3, 3);
  for(int i=0; i < 3; i++) {
    for(int j=0; j < 3; j++) {
      assert(m3[i][j]==res3[i][j]);
	}
  }

**Comment by marcelogarberoglio** [comment]
Sí, salvo casos particulares (por ejemplo si usamos una matriz que representa un tablero de ajedrez) deberíamos hacer un algoritmo que funcione tanto se si se usa en forma completa como así también si está definida de un tamaño máximo pero se usa una dimensión menor

**Comment by tomaspietravallo** [comment]
Genial, muchas gracias! Quedo claro
