### ISSUE TITLE
TP6 ej16

### ISSUE THREAD

**Issue by ldicandia** [PI-ITBA/2023_02#12]
buenas, queria saber si estaba bien hecho y si habria alguna forma de hacerlo con mejor estilo.
![Screenshot_1](https://github.com/PI-ITBA/2023_02/assets/128986084/e79ce83e-6d88-4437-99bc-1caae6fead1f)
![Untitled](https://github.com/PI-ITBA/2023_02/assets/128986084/c19a6ead-9723-4e79-bea2-c9151983aedb)

**Comment by marcelogarberoglio** [comment]
Sí, se podría mejorar un poco.
Por un lado en cuanto a eficiencia, el for interno, que recorre una fila sí o sí se hace hasta el final, aunque ascend y decend sean falsos
Por otro lado, tenés casos especiales para los extremos de cada fila. Pensá que si bien estás recorriendo una matriz, lo que te interesa saber es si el elemento actual es mayor o menor que el anterior que hayas visitando, ya sea que el anterior sea de esta fila o de la fila anterior.
