### ISSUE TITLE
2022 1Q EJ 1

### ISSUE THREAD

**Issue by ldicandia** [PI-ITBA/2023_02#16]
Estaria Bien resuelto asi?
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/90a84512-c788-44eb-828f-bcc54e6ec347)
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/f8098096-bd6a-40a5-8162-152cd0e424c4)

**Comment by marcelogarberoglio** [comment]
Sí, está muy bien.
