### ISSUE TITLE
Ej Wordle 1P 1C 2023

### ISSUE THREAD

**Issue by MCortesTey** [PI-ITBA/2023_02#19]
Buenas, queria consultar por el ejercicio 3 ya que el enunciado me genera duda en cuanto si es que es necesario o no chequear ciertos parametros como la cantidad de intentos, o verificar que las letras sean mayusculas o minusculas. Por otro lado, interpreté que la matriz de respuesta estaria dada como parametro pero no se si es correcto. Dejo mi codigo para ver si necesita alguna corrección, gracias.

`
int wordle(char palab[COLS], char mat[][COLS], int intentos, char resp[][COLS])
	{
		int i;
		if (intentosinvalido(intentos))
		{
			return 0;
		}
		for (i = 0; i < FILS && i < intentos; i++)
		{
			for (int j = 0; j < COLS; j++)
			{
				if (estaLetra(mat[i][j], palab))
				{
					if (palab[j] == mat[i][j])
					{
						resp[i][j] = 'V';
					}
					else
					{
						resp[i][j] = 'A';
					}
				}
				else
				{
					resp[i][j] = 'G';
				}
				
			}
			if (todoOk(resp[i]))
				{
					return i;
				}
		}
		return -1;
	}

	int intentosinvalido(int intentos)
	{
		return !(intentos > 0 && intentos <= FILS);
	}

	int estaLetra(char c, char palabra[COLS])
	{

		for (int i = 0; i < COLS; i++)
		{
			if (c == palabra[i])
			{
				return 1;
			}
		}

		return 0;
	}

	int todoOk(char resp[COLS])
	{
		for (int i = 0; i < COLS; i++)
		{
			if (resp[i] != 'V'){
				return 0;
			}
				
		}
		return 1;
	}
`

**Comment by marcelogarberoglio** [comment]
El prototipo de wordle es el correcto, interpretaste bien.
No era necesario validar la cantidad de internos, por lo tanto podrías sacar la validación y este for
for (i = 0; i < FILS && i < intentos; i++)
podría ser
for (i = 0; i < intentos; i++)
(de hecho, si nates hiciste la validación, tampoco sería necesario controlar i<FILS, ya que validaste que intentos sea <=FILS)

Cuando hacés
if (estaLetra(mat[i][j], palab))
{
if (palab[j] == mat[i][j])

primero buscás en toda la palabra, y luego ves si coincide en la posición, podrías hacer al revés, para no recorrer sin necesidad.
También se podría modularizar un poco más, hay mucho código en wordle, lo cual hace más probable que tenga errores difíciles de ver hasta que no se prueba el funcionamiento.
Te dejo una posible solución para que compares

```c
#include <stdio.h>
#include <assert.h>
#include <string.h>

#define FILS 6
#define COLS 5

enum Colors {GREEN='V', YELLOW='A', GREY='G'};

int wordle(const char *, const char [][COLS], int, char [][COLS]);
static int wordleRow(const char [COLS], const char *, char [COLS]);
static int wordleLetter(const char *, char, int);

int
wordle(const char * secretWord, const char inputMatrix[][COLS], int inputDim, char outputMatrix[][COLS]) {
    int i, greenRow;
    for(i = 0, greenRow = 0; i < inputDim && !greenRow; i++) {
        greenRow = wordleRow(secretWord, inputMatrix[i], outputMatrix[i]);
    }
    return greenRow ? i : -1;
}

static int
wordleRow(const char * secretWord, const char inputRow[COLS], char outputRow[COLS]) {
    int i, greenLetter;
    for(i = 0, greenLetter = 1; i < COLS; i++) {
        outputRow[i] = wordleLetter(secretWord, inputRow[i], i);
        greenLetter &= outputRow[i] == GREEN;
    }
    return greenLetter;
}

static int
wordleLetter(const char * secretWord, char inputLetter, int inputIndex) {
    if(secretWord[inputIndex] == inputLetter) {
        return GREEN;
    }
    if(strchr(secretWord, inputLetter) != NULL) {
        return YELLOW;
    }
    return GREY;
}
```
