### ISSUE TITLE
TP3 Ejercicio 5

### ISSUE THREAD

**Issue by emitchellitba** [PI-ITBA/2023_02#2]
Tengo la duda de si hay alguna manera mas eficiente/mejor estilo de resolver el ejercicio 5. Lo que se me ocurrio hacer es lo siguiente
`if (a>=65 && a<=90  && a!=65 && a!=69 && a!=73 && a!=79 && a!=85)
	printf("El caracter %c es una consonante mayúscula \n", a);`

**Comment by ImNotGone** [comment]
Por estilo, te pido por favor usen los ascii, asi es mas legible el codigo, 65 o 90 no tienen ningun significado claro fuera de contexto.

Para que sea mas legible todavia podrias definir una macro, pero nose si lo vieron.

Por otro lado, considerando lo de la eficiencia podrias excluir la 'A' del primer >= si es que queres ahorrarte 1 comparacion, aunque por claridad creo que no lo haria.

Quedaría si excluis la A en la primera comparación
```c
if(a >= 'B' && a <='Z' && a != 'E' && a != 'I' && a != 'O' && a != 'U') {
   // el print
}
```
O si no
```c
if(a >= 'A' && a <='Z' && a != 'A' && a != 'E' && a != 'I' && a != 'O' && a != 'U') {
   // el print
}
```
