### ISSUE TITLE
ej 1 Rec 2019 2Q

### ISSUE THREAD

**Issue by ldicandia** [PI-ITBA/2023_02#21]
Buenas, queria saber si en este tipo de ejercicios que usamos vector de apariciones hace falta castear el (int) o no porq me tiraba un warning.
y si la parte b) del ejercicio estaria bien poner char *p = NULL como ejemplo que asegure que aborta en ejecucion.
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/3c96f394-be5e-45c8-98ea-2df97caaa722)
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/f2865475-2e12-4799-a370-4dbfbde97807)

**Comment by ImNotGone** [comment]
En cuanto a lo primero sin castear tengo entendido que funcionaria igual, si es eso lo que te preguntabas. Es ideal de todas formas eliminar las warnings para asegurar el comportamiento correcto. En este caso podes hacer lo que hiciste (castear) o usar una variable int asignandole el valor de s[i] que escencialmente seria lo mismo. 
```c
int a = s[i];
vec[a];
```
para el b) seria un string NO modificable, te lo dejo para que lo pienses, pero si no te sale pregunta denuevo

**Comment by ldicandia** [comment]
un const char *s?

**Comment by ImNotGone** [comment]
No, con const char el calificador se descartaria al pasarselo a la funcion, ya que la misma toma un char *

**Comment by ImNotGone** [comment]
Por las dudas te dejo que la solucion al b es hacer
char * s = "algo";
de esta forma el string se genera en una zona de memoria constante, por lo que al intentar modificarlo (ya sea porque hay que borrar algo o simplemente x agregar el 0 final), el programa va a fallar en ejecucion
