### ISSUE TITLE
TP6ej20 Sudoku

### ISSUE THREAD

**Issue by felipeboya** [PI-ITBA/2023_02#27]
Hola, estoy un poco trabado con el ejercicio de sudoku del TP6. En principio el código falla y no puedo encontrar el error ( solo falla en el segundo assert del test que esta en el campus ) y ademas creo que tiene mas ciclos for de los que debería pero no se como podría hacerlo usando menos. Se me ocurrió usar un vector de apariciones pero no termino de entender como implementarlo para hacer menos recorridos de las que hago ( si es que se puede ). 

```
#define DIM 9
#define DIMSUBM 3

#define IN_RANGE(x) ( (x) > 0 && (x) < 10 )

int sudokuSolver(char m[][DIM]){

    for ( int i = 0; i < DIM; i+=3){
        for ( int j = 0; j < DIM; j+=3){
            if ( !checkSubM(m, i, j) )
                return 0;
        }
    }

    for ( int i = 0; i < DIM; i++){
        if ( !checkRow(m[i]) )
            return 0;
    }

    for ( int j = 0; j < DIM; j++){
        if ( !checkCol(m, j) )
            return 0;
    }

    return 1;
}

int checkSubM( char m[][DIM], int fil, int col){   //verifica que en la submatriz correspondiente a m[i][j] no halla repetidos
    int colIni = col;                                                   // y que esten todos en rango
    for ( int k = 0; k < DIM -1; k++) {
        for (int i = fil; i < i + DIMSUBM; i++) {
            for (int j = col; j < col + DIMSUBM; j++) {

                if (!IN_RANGE(m[i][j]))
                    return 0;

                if (!(i == fil && j == col)) {
                    if (m[fil][col] == m[i][j])
                        return 0;
                }
            }
        }
        col++;
        if ( col % DIMSUBM == 0){
            fil++;
            col = colIni;
        }
    }
    return 1;
}

int checkRow( const char v[] ){
    for ( int i = 0; i < DIM - 1; i++ ) {
        for (int j = i+1; j < DIM; j++) {
            if (v[i] == v[j])
                return 0;
        }
    }
    return 1;
}

int checkCol( const char m[][DIM], int col){
    for ( int i = 0; i < DIM - 1; i++){
        for ( int j = i+1; j < DIM; j++) {
            if ( m[i][col] == m[j][col] )
                return 0;
        }
    }
    return 1;
}
```

**Comment by marcelogarberoglio** [comment]
Está muy complicada de seguir checkSubM, muy complejo el código para simplemente recorrer una sub-matriz de 3x3
Para evitar recorridos podrías usar un vector de apareciciones de 9 lugares donde marcás si ya apareció el 1, el 2, etc. Eso lo hacés para cada fila, para cada columna y para cada sub-matrriz. 
Para recorrer la submatriz sólo deberías hacer

int checkSubM( char m[][DIM], int fil, int col){   //verifica que en la submatriz correspondiente a m[i][j] no halla repetidos
    int colIni = col;                                                   // y que esten todos en rango
    for ( int k = fil; k <fil+DIMSUBM ; k++) {
        for (int i = col; i < col DIMSUBM; i++) {    

En esta última línea tenías un error, ya que al hacer

           for (int i = fil; i < i + DIMSUBM; i++) {

la condición siempre es verdadera.

**Comment by felipeboya** [comment]
Marce, ahi probe lo que me dijiste y tambien corregi el error pero igualmente no pasa el test, se sigue trabando en el segundo assert. 

```
int sudokuSolver(char m[][DIM]){

    for ( int i = 0; i < DIM; i+=3){
        for ( int j = 0; j < DIM; j+=3){
            if ( !checkSubM(m, i, j) )
                return 0;
        }
    }

    for ( int i = 0; i < DIM; i++){
        if ( !checkRow(m[i]) )
            return 0;
    }

    for ( int j = 0; j < DIM; j++){
        if ( !checkCol(m, j) )
            return 0;
    }

    return 1;
}

int checkSubM( char m[][DIM], int fil, int col){
    char num;
    char vecAp[DIM] = {0};

    for ( int i = fil; i < DIMSUBM + fil; i++ ){
        for ( int j = col; j < DIMSUBM + col; j++ ){

            num = m[i][j];

            if (!IN_RANGE(num))
                return 0;

            if ( vecAp[(int)num] != 0  ){
                return 0;
            }else {
                vecAp[(int)num] = num;
            }
        }
    }
    return 1;
}

int checkRow( const char v[] ){
    char vAp[DIM] = {0};

    for ( int i = 0; i < DIM; i++ ){
        char num = v[i];
        if ( vAp[i] != 0 ){
            return 0;
        }else {
            vAp[(int)num] = num;
        }
    }
    return 1;
}

int checkCol( const char m[][DIM], int col){
    char vAp[DIM] = {0};

    for ( int i = 0; i < DIM; i++ ){
        char num = m[i][col];
        if ( vAp[i] != 0 ){
            return 0;
        }else {
            vAp[(int)num] = num;
        }
    }

    return 1;
}

```

**Comment by felipeboya** [comment]
Ya encontre los errores. Tenia que poner el indice de los vectores de apariciones  que sea num - 1. Ahora pasa bien el testeo. 
Mas alla de eso el codigo estaria bien asi, en cuanto estilo y eficiencia?

**Comment by marcelogarberoglio** [comment]
Era restarle uno o definir los vector con DIM+1, para no estar restando todo el tiempo.
Así está bien.
Y con respecto a la consulta, depende del caso. Por ejemplo si querés saber si una matriz de NxN tiene todos los números entre 1 y NxN inclusive, es mejor crear un vector de chars de NxN elementos que recorrerla NxN veces, por ejemplo fijándose si está el 1, luego el 2, etc. o viendo si el elemento [0,0] está repetido, luego el [0,1], etc.

**Comment by felipeboya** [comment]
Perfecto gracias!
