### ISSUE TITLE
2022 2C Recu Ej 1

### ISSUE THREAD

**Issue by juanpalermo** [PI-ITBA/2023_02#28]
Buenas, perdon que moleste, tenia una duda sobre siguiente ej: 

-Escribir una función que reciba dos matrices cuadradas de enteros de dimensión DIM (DIM es una constante previamente definida) y determine si entre las dos matrices contienen todos los números entre 1 y 2 * N * N inclusive, sin repetir. En caso de cumplir con esa condición debe retornar 1, de lo contrario retorna 0 (cero).
<img width="568" alt="Captura de pantalla 2023-09-27 a la(s) 19 30 04" src="https://github.com/PI-ITBA/2023_02/assets/107368772/d24987fc-a834-48e8-9e11-38bb875699ce">

Estaria bien asi? Porque cuando lo estaba pesando, se me ocurrio de esta manera y de otra manera, la cual era hacerlo todo en una misma funcion. 

Saludos!

**Comment by marcelogarberoglio** [comment]
Está bien. También podría ser, en vez del 

if ( ! chequeo...

hacer directamente

 return chequeo(m1,aux) && chequeo(m2,aux);

**Comment by juanpalermo** [comment]
Muchas Gracias!!
