### ISSUE TITLE
1P1C2023 - ej 1

### ISSUE THREAD

**Issue by manuothatceguy** [PI-ITBA/2023_02#29]
Hola, quisiera saber si mi resolución es correcta. Estuve probándolo a mano (como si estuviera en el parcial) y por ahora no encontré caso en el que no me funcione.

Dejo a mano la consigna:
"Escribir la función elimina que recibe tres strings s1, s2 y s3 y elimina de s1 aquellos caracteres que están presentes en s2 o en s3 en la misma posición que en s1."

Esta es mi función:

```c
void elimina(char * s1, char * s2, char * s3){
    int i = 0, j = 0, fin2 = 0, fin3 = 0, i2 = 0, i3 = 0;    
    while(s1[i] != '\0' && (s2[i2] != '\0' || s3[i3] != '\0')){
        fin2 = (s2[i2] == 0);
        fin3 = (s3[i3] == 0);    

        if(!fin2 && s1[i] == s2[i2])
            i++;i2++;i3++;
        else if(!fin3 && s1[i] == s3[i3])
            i++;i2++;i3++;
        else if(s1[i]){
            s1[j++] = s1[i++];        
        }        
    }
    s1[j] = 0;
}
``` 
Gracias!

**Comment by manuothatceguy** [comment]
Me di cuenta que me falta hacer incrementos si no terminaron los strings 2 y 3. Debajo de ```c s1[j++] = s1[i++];```debería ir:
```c
i2 = fin2 ? i2 : i2+1;
i3 = fin3 ? 13 : 13+1;
```
o un if(!fin2) i2++; (¿cuál es mejor?)

**Comment by marcelogarberoglio** [comment]
Me parece que no está bien. Si s2 y s3 llegan al final antes que s1, salís del ciclo y colocás un cero final, perdiendo todo lo que seguía en s1

Además cuando hacés
 if(!fin2 && s1[i] == s2[i2])
            i++;i2++;i3++;

por más que los pongas en una misma línea, sólo i++ está dentro del if
y estás incrementando i3, tal vez salteando el cero final de s3.
Fijate de hacer alguna prueba con par de vectores de chars

**Comment by manuothatceguy** [comment]
Ahí me di cuenta lo que falla, aparte de la sintaxis de los if. Cuando hice las pruebas me olvidé de los && en la condición del while. Voy a corregir eso y seguir probando.

Gracias

**Comment by manuothatceguy** [comment]
Ahí corregí la función y probé la función con estos dos casos:

- Caso 1:
```c
char s1[] = "holaMundo";
char * s2 = "BuenMartes";
char * s3 = "hilo";
```
s1 después de la ejecución debería ser "oaundo".

- Caso 2:
```c
char s4[] = "Graciela";
char * s5 = "Beatriz";
char * s6 = "Grande";
```
s3 después de la ejecución debería ser "cila".

Acá la función corregida:
```c
void elimina(char * s1, char * s2, char * s3){
    int i = 0, j = 0, fin2 = 0, fin3 = 0, i2 = 0, i3 = 0;    
    while(s1[i] != '\0'){
        fin2 = (s2[i2] == 0);
        fin3 = (s3[i3] == 0);    

        if(!fin2 && s1[i] == s2[i2]){
            i++;
            i2 = fin2 ? i2 : i2+1;
            i3 = fin3 ? i3 : i3+1;        
        }

        else if(!fin3 && s1[i] == s3[i3]){
            i++;
            i2 = fin2 ? i2 : i2+1;
            i3 = fin3 ? i3 : i3+1;
        }
            
        else if(s1[i]){
            s1[j++] = s1[i++];
            i2 = fin2 ? i2 : i2+1;
            i3 = fin3 ? i3 : i3+1;
        }        
    }
    s1[j] = 0;
}
```

**Comment by marcelogarberoglio** [comment]
Está bien en cuanto al funcionamiento ahora, lo que no queda muy bien son expresiones de este tipo

 i2 = fin2 ? i2 : i2+1;

donde a i2 le podés asignás i2. Se puede reemplazar por 

if ( !fin2)  i2++;

o también por

 i2 += ! fin2;

**Comment by marcelogarberoglio** [comment]
Ah, y también está de más este if

 if(s1[i]){

porque siempre es verdadero, ya que si s1[i] es cero no entra al ciclo. 

Y estas dos líneas
           i2 = fin2 ? i2 : i2+1;
            i3 = fin3 ? i3 : i3+1;     
se hacen siempre, en todos los if y los else, por lo que deberían estar una sola vez, después del if

**Comment by manuothatceguy** [comment]
Claro, tenés razón. Como fui "emparchando" el código me olvidé de esos detalles. Gracias!
