### ISSUE TITLE
Ej 3 2022 2C

### ISSUE THREAD

**Issue by ldicandia** [PI-ITBA/2023_02#30]
Buenas, este ejercicio me salio de dos maneras distintas pero no se cual seria la manera mas eficiente. la primera es con un vector de apariciones y la segunda con strchr. pero me confundio el enunciado que decia q text puede ser larga pero chars es corta.
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/a3b8b00b-7d41-4ba8-a4b3-b7663ae09e79)
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/52718425-d1bb-4b85-aff9-cd41a5e0b8e2)

**Comment by marcelogarberoglio** [comment]
Como el enunciado aclara que chars es un string corto, ambas están bien.
Si chars pudiera ser también un texto extenso, la opción correcta sería elimChars2

**Comment by ldicandia** [comment]
perfecto, gracias.
