### ISSUE TITLE
TP07_ej8 (Bingo)

### ISSUE THREAD

**Issue by manuothatceguy** [PI-ITBA/2023_02#38]
Hola, tengo un inconveniente importante cuando genero los cartones. Mi función ```generarCarton``` es la siguiente:
```c
void generarCarton(TipoCarton player){
    char numeros[CANT_BOLILLAS + 1] = {0};
    int num;
    randomize();
    for(int i = 0; i < CANT_FILS; i++){
        for(int j = 0; j < CANT_COLS; j++){
            do
            {
                num = randInt(1,CANT_BOLILLAS);
            } while (numeros[num] != 0);
            numeros[num] = 1;
            player[i][j] = num;
        }
    }
    return;
}
```
Esta función me los genera exactamente iguales, puede ser que pase eso porque la seed es la misma? 
Debería usar la función sleep()? 

Gracias!

**Comment by marcelogarberoglio** [comment]
La función     randomize();   se debe invocar en el main, una sola vez. Como tarda muy poco en generar los cartones cada vez que llamás a la función está fijando la misma semilla para cada uno.

**Comment by manuothatceguy** [comment]
Ahh, perfecto. Mil gracias!!!
