### ISSUE TITLE
autoevaluacion8

### ISSUE THREAD

**Issue by felipeboya** [PI-ITBA/2023_02#45]
Hola, tengo una consulta de una de las preguntas de la autoevaluación de structs. No entiendo porque el código tiene en la linea 24 error de compilación (me dice que punto2 no esta declarado, y si le saco el asterisco o solo los parentesis tambien ) y en la siguiente de ejecución. Y mas alla de que den distintos tipos de errores, no entiendo porque dan error. 

```
 1   #include <stdio.h>                                     
 2
 3   typedef struct { 
 4       int a;    
 5       int b;  
 6   } Coordenada;    
 7
 8   typedef Coordenada * PCoord;    
 9
10   typedef struct  
11   {     
12      char * nombre;     
13      Coordenada punto1;     
14      PCoord punto2;  
15   } TipoX;    
16 
17   int  
18   main(void)  
19   {
20        TipoX var1;           
24        var1.(*punto2).b = 50;    
25        var1.punto2->b = 50;        
26 
27        return 0;  
28   }  

```

**Comment by ImNotGone** [comment]
Es directamente un error de sintaxis ya que la unica forma de acceder a un campo de una estructura es que el mismo este exactamente despues del . o de la ->
es decir es invalido:
- _var1.(punto2)_

en este caso ademas esta intentando hacer lo que hace exactamente en la linea siguiente, que seria desreferenciar y luego acceder a un campo.
las formas que tendria de hacer eso son las siguientes:
```c
var1.punto2[0].b = 50;
var1.punto2->b = 50;
// si quisieras hacerlo mas "similar" al que te falla, seria algo asi
PCoord coord = var1.punto2;
(*coord).b = 50;
```

**Comment by felipeboya** [comment]
Ok gracias ahí entendí el primero que da error de compilación, pero no me quedo claro porque la linea 25 genera un error de ejecución, porque segun lo que me dijiste si hago var1.punto2->b = 50 entiendo que deberia funcionar pero no anda, y tambien probe con var1.punto2[0].b = 50 y da error de ejecucion tambien.

**Comment by felipeboya** [comment]
Ahi estuve viendo y puede ser que sea porque no esta inicializado el puntero no? Pero a donde lo deberia hacer apuntar en este caso para que funcione bien?

**Comment by felipeboya** [comment]
Listo ya lo entendi gracias. Lo hago apuntar al heap antes de usarlo y listo.
