### ISSUE TITLE
TP 11 - MoveToFront funcion get 

### ISSUE THREAD

**Issue by juanpalermo** [PI-ITBA/2023_02#58]
Buenas, como andan?? estaba haciendo la funcion get de este TAD y queria saber si estaba bien, tmb queria saber si necesito hacer una funcion de eliminar el elem que estaba en la posicion antes de pasar primero.  
<img width="494" alt="Captura de pantalla 2023-11-08 a la(s) 16 14 30" src="https://github.com/PI-ITBA/2023_02/assets/107368772/cdc626be-cb1a-4023-8c2f-11bcf1511913">

**Comment by ImNotGone** [comment]
- _Para saber si el elemento esta usa la funcion compare_ tenes que recorrer los elementos y buscar si esta presente, no solo preguntar por el primero.
- _Si el elemento estaba lo ubica al principio_ si lo encontraste lo moves.

**Comment by ImNotGone** [comment]
Sry no vi la ultima parte, podrias hacerlo con una funcion auxiliar static, pero no es necesario liberar el nodo, simplemente reasignar los punteros en la lista para que el mismo se reubique

**Comment by marcelogarberoglio** [comment]
Hay varios errores en la función. Para empezar un error de tipos, ya que moveToFrontADT debería ser un puntero a struct moveToFrontCDT, muy similar al struct listCDT que se hizo en clase. Donde entre otras cosas ese struct contiene first, que debería ser el puntero a un struct node (first no debe ser de tipo moveToFrontADT), por lo que no estaría bien hacer
auxNode->tail - moveToFront, ya que son de distinto tipo
La función sólo compara el primero en vez de recorrer y ver si lo encuentra
El primero puede ser NULL, si la lista está vacía
moveToFront->first sería el puntero al primero nodo, no el elemento que está en el primer nodo

**Comment by juanpalermo** [comment]
perfecto! ahora lo pienso de nuevo, muchas gracias!
