### ISSUE TITLE
CollectionADT duda enunciado

### ISSUE THREAD

**Issue by juanpalermo** [PI-ITBA/2023_02#59]
buenas, como andan? en CollectionADT, me dicen lo siguiente: 
/* Crea una nueva colección de elementos genéricos
** Inicialmente la colección está vacía
** Cada elemento a insertar será de tipo elemType
** No hay un límite para la cantidad de elementos a insertar */
collectionADT newCollection( ¿? );

cuando me dicen ¿?, pense en la funcion compare o void, mi duda es si la funcion compare es solo para listas o es para todas??

**Comment by marcelogarberoglio** [comment]
Buenas, antes que nada tendrías que copiar el enunciado original. Bajo ese mismo nombre hay distintos ejercicios de parciales.
La función de comparación no es sólo para listas, sino para cualquier TAD que use elementos genéricos.
Te recomiendo que antes de hacer ejercicios de parciales hagas los de la guía.

**Comment by juanpalermo** [comment]
uh perdon, me olvide de subir el enunciado. ah buenisimo, muchas gracias!
