### ISSUE TITLE
TP_04 Ej 1)d

### ISSUE THREAD

**Issue by emitchellitba** [PI-ITBA/2023_02#6]
Hola buenas tardes, tenia una consulta con el 1)d del TP_04. Cuando imprimi e, obtengo el cubo de 4 (64), en cambio en f obtengo el cubo de 3 (27). Eso va cambiando respecto de la posicion del operador de incremento ++, pero no entiendo porque incrementa a "a" unicamente si va antes del lvalue.

```c
d = 3;
	e = cubo ( ++d );
    printf("%d\n", e);
	d = 3;
	f = cubo ( d++ );
    printf("%d\n", f);

**Comment by marcelogarberoglio** [comment]
Al usar un pre-incremento (++a) primero se incrementa la variable y luego se usa en la expresión. En cambio al hacer a++ primero se usa el valor de a en la expresión y luego se incrementa, entonces hacer

f = cubo(++d);

es lo mismo que hacer

d=d+1; // primero lo incremento
f = cubo(d); // luego lo uso para pasárselo a la función


En cambio hacer

f = cubo(d++);

es lo mismo que hacer

f = cubo(d); // primero uso d
d=d+1; // luego lo incremento

**Comment by emitchellitba** [comment]
Muchisimas gracias.

**Comment by emitchellitba** [comment]
Muchisimas gracias
