### ISSUE TITLE
EJ 15 tp11

### ISSUE THREAD

**Issue by ldicandia** [PI-ITBA/2023_02#62]
Buenas, me tira un error en esos asserts del testeo (lineas 52 y 60) y no me queda muy claro porque. yo creo q es por algo del get pero no lo puedo ver.
![Screenshot_4](https://github.com/PI-ITBA/2023_02/assets/128986084/eac45d56-e84d-4333-9073-75c44cfd0294)
![adt](https://github.com/PI-ITBA/2023_02/assets/128986084/bf1d201e-5207-4fe4-8648-6cd5a733e710)
![test](https://github.com/PI-ITBA/2023_02/assets/128986084/52273ea7-0048-4849-a81a-3753651b9fd9)
![Screenshot_3](https://github.com/PI-ITBA/2023_02/assets/128986084/b1326651-ec46-40cd-96b3-e6d279f7f7e5)

**Comment by ImNotGone** [comment]
No estas dovolviendo lo que hay en la lista, eztas devolviendo lo que recibiste como entrada en la funcion. Como el cmp solo compara por codigo, te pasaron code = 3 name = "cuatro" y vos devolviste eso

**Comment by ldicandia** [comment]
osea, asi?
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/5ee7a686-b905-41bf-9296-2659c38ddc85)

**Comment by ImNotGone** [comment]
Claro el tema igual es q en la funcion buscar elem, no devolves el elem q vas a liberar y dsp el nuebo primer nodo tmb lo creas con lo q te pasan en la funcion. Lo q deberias hacer es en buscar elem devolver lo q tenia el nodo o directamente devolver el nodo ese (actualizando los punteros) sin liberarlo

**Comment by ldicandia** [comment]
se me ocurre hacer un TList flag pero nose como cubrir el caso de q devuelva null
![Screenshot_3](https://github.com/PI-ITBA/2023_02/assets/128986084/b64773b7-2c34-4fe3-a811-26028b172df7)

**Comment by ImNotGone** [comment]
Inicia TList flag en NULL antes de el llamado a la funcion. Si despues de el llamado no esta en NULL es porque le cargaste algo.

**Comment by ldicandia** [comment]
si, habia intentado con eso pero me tiraba segmentation fault y ahora lo corregi y me quedo asi pero sigue tirando "3 cuatro" y aborta con el assert de strcmp "tres"
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/e2734abc-92fb-4ce3-96d5-9a31509e49f9)
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/bc0032a6-258a-4a80-91bd-aa1ca65b1515)

**Comment by ImNotGone** [comment]
```c
(*flag)->elem =list->elem;
```
Sino seguis cargando lo q te pasan x parametro

**Comment by ldicandia** [comment]
ahhhh ahi entendi perfecto muchas gracias.
