### ISSUE TITLE
Pregunta tp5_Ej2d

### ISSUE THREAD

**Issue by NaPrado** [PI-ITBA/2023_02#7]
![image](https://github.com/PI-ITBA/2023_02/assets/141145234/41ee03b5-4f86-4f17-a817-01b72e7d819a)
![image](https://github.com/PI-ITBA/2023_02/assets/141145234/7e12c26e-61c4-4a07-9a27-2abde9f2df7d)

Quisiera consultar si para este ejercicio, las entradas del estilo "090" se consideran capicuas por poner el cero o se considera 90 y por lo tanto no es capicua. En caso de que 090 se capicua entonces tengo que usar un getchar?

**Comment by ImNotGone** [comment]
el 0 a la izq no aporta nada, el numero es 90

**Comment by NaPrado** [comment]
Gracias
