### ISSUE TITLE
Duda parcial 14/06/2019

### ISSUE THREAD

**Issue by juanpalermo** [PI-ITBA/2023_02#72]
Buenas, como andan? perdon que moleste, tenia una duda sobre este ejercicio (adjunto ej en el archivo). Mi duda es que tiene funciones para iterar pero esta la funcion get que swapea con el anterior. Que me conviene listas o vector? pregunto esto porque para iterar conviene listas pero lo de la funcion get me mato jaja. 
Saludos,

[14.06.2019.pdf](https://github.com/PI-ITBA/2023_02/files/13385176/14.06.2019.pdf)

**Comment by marcelogarberoglio** [comment]
Contestado en la consulta. Se puede hacer con ambos pero conviente usar vectores, es más simple.

**Comment by juanpalermo** [comment]
Muchas gracias!
