### ISSUE TITLE
Parcial 1 2018 Ej 3

### ISSUE THREAD

**Issue by tomaspietravallo** [PI-ITBA/2023_02#79]
Buenas! Tenia una duda sobre el siguiente ejercicio (en cuestiones de eficiencia)

> a) Escribir una función elimina que recibe dos strings y elimina del primero todos los caracteres
que aparecen en el segundo string.
>
> Ejemplos de uso:
>
> ```c
> char s[] = "Un string. Con diversas letras y simbolos!!";
> elimina(s, "aeiou"); // s es ahora "Un strng. Cn dvrss ltrs y smbls!!"
> elimina(s, " !."); // s es ahora "UnstrngCndvrssltrsysmbls"
> elimina(s, "aeiou"); // s ahora no cambia
> ```
>
> b) Escribir un ejemplo de invocación que asegure que el programa aborta en ejecución. Explicar por
qué aborta.

Seria mejor marcar todas las apariciones del string 2 en un vector (algo del estilo [1]), o ir buscando por cada char [2] ?

La consigna no dice nada mas en cuestiones de longitud del string, esa es la consigna completa. Si dijera que se espera que los strings fueran muy largos como lo plantearía? y en el caso de que el string con letras a eliminar fuera **muy** largo?

---

<details>

<summary>[1] Codigo con apariciones</summary>

```c
#define CANT_CHARS 256

void elimina(char *s1, const char * s2){
  //arma vector de apariciones con 0
  char apariciones[CANT_CHARS]={0};
  marcoApariciones(s2, apariciones);
  int r=0, w=0;
  while(s1[r]){
    //si la letra no estaba en el segundo string, la copio
    if(apariciones[(int)s1[r]]==0){
      s1[w++]=s1[r];
    }
    r++;
  }
  s1[w]='\0';
  return ;
}

// marca con 1 si el caract aparece en el segundo string
void marcoApariciones(const char * s2, char apariciones[]) {
  int i=0;
  while(s2[i]){
  if(apariciones[ (int)s2[I]] == 0 ) {
    apariciones[(int)s2[i]]=1;
  }
  i++;
  }
  return;
}
```

</details>

---

<details>

<summary>[2] Buscando por cada char (usando strchr) </summary>

```c

int deboEliminar(char c, char * elim) {
  char * p = strchr(elim, c);
  if ( p == NULL)
     return 0;
  return 1;
}

void elimina(char *s1, const char * s2){
  int r=0, w=0;
  while(s1[r]){
    //si la letra no estaba en el segundo string, la copio
    if( deboEliminar( s1[r], s2 ) == 0 ) {
      s1[w++]=s1[r];
    }
    r++;
  }
  s1[w]='\0';
  return ;
}

```

</details>

---

La pregunta en parte se origino porque el Ej 28 de la Guia 6 (eliminaVocales) utiliza strchr para identificar las vocales en el texto y el ejercicio parecía tener algo de similitud

Gracias!

**Comment by marcelogarberoglio** [comment]
Si no aclara nada cualquiera de las dos opciones está bien. Si aclarara que ambos strings pueden ser extensos (sobre todo el segundo), entonces conviene la primera versión.
El único cambio que haría es de estilo: en la función marcoApariciones reemplazaría el while por un for, lo mismo en elimina
