### ISSUE TITLE
TP4 ej11

### ISSUE THREAD

**Issue by augustolanari** [PI-ITBA/2023_02#8]
Buenas tardes, me gustaría saber si esta resolución del problema es correcta en cuanto a la eficiencia. si no es ¿cómo seria mejor?

	Escribir una función que reciba tres parámetros de entrada de tipo entero y que devuelva en su nombre el mayor de ellos. 
(En 2 líneas)

int mayor(int a, int b, int c){
    int d;
    d= a > b ? a:b;
    d= d > c ? d:c;
    return d;
}

Desde ya muchas gracias. Saludos.

**Comment by marcelogarberoglio** [comment]
En cuanto a eficiencia está bien. En cuanto a estilo, en esta proposición
d= d > c ? d:c;
estás diciendo: "si d es mayor a c, asignale a d el valor de d"

Tal vez podrías hacer algo parecido pero directamente en el return, o sea

int mayor(int a, int b, int c){
int d;
d= a > b ? a : b;
return  d > c ? d : c;
}

**Comment by augustolanari** [comment]
Buenísimo, muchas gracias! Disculpe por haberle interrumpido su sábado.
