### ISSUE TITLE
Ejercicio 1 2R 2P 2022

### ISSUE THREAD

**Issue by Martin192003** [PI-ITBA/2023_02#84]
Hola Marce, disculpa de nuevo las molestias, era para consultarte si en los ejercicios de este estilo si no había problemas con hacer la función tipo TList o void, porque cómo nos pide eliminar de la misma lista no se si estaría bien el hacer de esta manera que lo hice o sería de otra.
![image](https://github.com/PI-ITBA/2023_02/assets/146043951/f51c38e0-43f8-4a79-bc14-afa98858a269)
`TList sortedList(TList list){

	if(list->tail==NULL){

		return NULL;

	}

	list->tail=sortedList(list->tail);

	if(list->elem>=list->tail->elem){

		TList aux=list->tail;

		free(list);

		list=aux;

		return list;

	}

	return list;

}`

**Comment by ImNotGone** [comment]
falla si
```c
list == NULL
```
Ademas si tiene un solo elemento deberia devolver el propio
osea
```c
if(list == NULL || list->tail == NULL) {
    return list;
}
```
se entiende?
si necesitas te armo el test sino

**Comment by Martin192003** [comment]
Ahhh claro, si me lo re olvidé al list==NULL, gracias Gonza!!, lo otro estaría bien?

**Comment by ImNotGone** [comment]
Si el codigo te quedo asi: entonces pareceria estar bien. No lo probe en la compu, pero hice el seguimiento en el aire.
En el examen te recomiendo que hagas el seguimiento en papel si podes para verificar lo q estes haciendo con algun ejemplo q se te ocurra y por lo menos los que te da la catedra.
```c
TList sortedList(TList list){
    if(list == NULL || list->tail==NULL){
        return list;
    }
    list->tail=sortedList(list->tail);
    if(list->elem>=list->tail->elem){
        TList aux=list->tail;
        free(list);
        /* esta asignacion la podes sacar,
        ** retornando derecho aux pero 
        ** tampoco es problema si te parece mas claro
        ** list=aux;
        ** return list;
        */
        return aux;
    }
    return list;
}
```
