### ISSUE TITLE
TP11 Ej 17

### ISSUE THREAD

**Issue by augustolanari** [PI-ITBA/2023_02#89]
Buenas Tardes, tengo una consulta sobre este ejercicio, en el assert falla. Quisiera saber si la función cpy y su implementacion es el correcta, creo que ahi puede estar la falla. Desde ya muchas gracias.

`#define BLOQUE 50
typedef struct frases{
    char* frase;
    char usado;
}frases;
typedef struct phrasesCDT{
    frases * frases;
    size_t size;
    size_t desde;
    size_t dim;
    size_t hasta;
}phrasesCDT;

phrasesADT newPhrasesADT(size_t keyFrom, size_t keyTo){
    if(keyTo<keyFrom){
        return NULL;
    }
    phrasesADT new= malloc(sizeof(phrasesCDT));
    int c;
    c=keyTo-keyFrom;
    new->frases=calloc(c, sizeof(frases));
    new->dim=c;
    new->desde=keyFrom;
    new->hasta=keyTo;
    new->size=0;
    return new;
}

void freePhrases(phrasesADT ph){
    for(int i=0;i<ph->dim;i++){
        free(ph->frases[i].frase);
    }
    free(ph->frases);
    free(ph);
}

static char* cpy(char* dest, const char*origen){
    int i;
    for(i=0; origen[i]; i++){
        if(i%BLOQUE==0){
            dest=realloc(dest, i+BLOQUE);
        }
        dest[i]=origen[i];
    }
    dest=realloc(dest, i);
    return dest;
}

int put(phrasesADT ph, size_t key, const char * frase){
    if(ph->desde>key || ph->hasta<key){
        return 0;
    }
    if(ph->frases[key-ph->desde].usado==0){
    ph->size++;        
    }
    ph->frases[key-ph->desde].usado=1;
    ph->frases[key-ph->desde].frase= cpy(ph->frases[key-ph->desde].frase, frase);
    return 1;
}

char * get(const phrasesADT ph, size_t key){
    char * toReturn;
    toReturn= cpy(toReturn, ph->frases[key-ph->desde].frase);
    return toReturn;
}

size_t size(const phrasesADT ph){
    return ph->size;
}

char *concat(const phrasesADT ph, size_t from, size_t to){
    char * toReturn;
    for(int i=from-ph->desde; i<to-ph->desde; i++){
        if(ph->frases[i].usado){
            toReturn= cpy(toReturn, ph->frases[i].frase);
        }
    }
    return toReturn;
}

char* concatAll(const phrasesADT ph){
    return concat(ph, 0, ph->hasta-ph->desde);
}

`

**Comment by marcelogarberoglio** [comment]
Por lo pronto en cpy falta dl cero final.
Fijate para la próxima de colocar ```c   antes del código y ```  al final, para que quede así

```c
char *concat(const phrasesADT ph, size_t from, size_t to){
char * toReturn;
for(int i=from-ph->desde; idesde; i++){
if(ph->frases[i].usado){
toReturn= cpy(toReturn, ph->frases[i].frase);
}
}
return toReturn;
}

char* concatAll(const phrasesADT ph){
return concat(ph, 0, ph->hasta-ph->desde);
}
```

**Comment by augustolanari** [comment]
Buenisimo, no sabia como hacer eso. Entonces modifico para que copie el 0 al final, y en concat solo al final de todo el string y estaria bien ¿no? Muchas gracias!

**Comment by marcelogarberoglio** [comment]
No sé si es el único error, tendrías que corregir eso y probarlo, con el flag de sanitizer.

**Comment by augustolanari** [comment]
Perfecto, gracias!
