### ISSUE TITLE
TP6 EJ4

### ISSUE THREAD

**Issue by ldicandia** [PI-ITBA/2023_02#9]
tengo una duda del enunciado
![image](https://github.com/marcelogarberoglio/PI/assets/128986084/0f02e05e-c017-4700-84fd-95423a9d51bc)
la funcion tiene que borrar los repetidos o deja uno y borra el resto de los repetidos?

me refiero por ejemplo: 
{3, 5 , 1, 3, -3, 3, 5, 1} 
dejaria:
{3, 5, 1, -3, 1} o {-3}

yo asumo q es la primera por los testeos pero en el video del drive hace la segunda y me tira error en los asserts.

por ejemplo para dimOrig = 4 dejaria {5, 1} y salta el assert de res[0] == 3 usando el codigo del video

**Comment by ImNotGone** [comment]
La primera deberia ser. Y con dimOrig = 4 deberia dejar {3, 5, 1} si estas laburando sobre el mismo vector. Por lo que la dim de salida seria 3

**Comment by ImNotGone** [comment]
> La primera deberia ser. Y con dimOrig = 4 deberia dejar {3, 5, 1} si estas laburando sobre el mismo vector. Por lo que la dim de salida seria 3

Se me escapo, la primera opcion que pusiste tiene un 1 de mas. Lo correcto seria 
{3, 5, 1, -3} para ese caso.

**Comment by ldicandia** [comment]
![image](https://github.com/PI-ITBA/2023_02/assets/128986084/3bcd83c7-eeb0-4393-b5c4-562f64c97b9b)
esta version estaria bien entonces?

**Comment by ImNotGone** [comment]
parece q si. :D
